### ISSUE TITLE
Legend for H/I/L and colour codes

### ISSUE THREAD

**Issue by alpascal** [joinbox/infect#26]
The colour and letters of the tiles need a legend. Does anyone have a good idea for where to put it?
I can think of 3 possibilities:
1. show it in a bubble on clicking on a tile after mouseover enlargement
2. put it in about (which may be the most convenient option for the moment)
3. put it somewhere else discretely on the site (although that might look ugly)

**Comment by fxstr** [comment]
For the about text, see https://github.com/joinbox/infect/issues/24 – implement together.

**Comment by alpascal** [comment]
As there is some ambiguity on how to use cut-offs for antibiotic resistance, I've opened another issue to discuss the idea of a heatmap-like matrix using more colours from green over orange to red.
