### ISSUE TITLE
Changing "INFEKT" to "INFECT" on frontend

### ISSUE THREAD

**Issue by alpascal** [joinbox/infect#28]
Changing "INFEKT" to "INFECT" on frontend:
![unbenannt](https://cloud.githubusercontent.com/assets/1735457/6866778/ebc02f66-d47b-11e4-821b-25267ed5ad76.JPG)

**Comment by fxstr** [comment]
![image](https://cloud.githubusercontent.com/assets/1211144/7681548/5e57d75e-fd71-11e4-998b-a9087c6ae5de.png)
(Release pending).
