### ISSUE TITLE
Combined compounds not displayed correctly on frontend

### ISSUE THREAD

**Issue by alpascal** [joinbox/infect#29]
Our 2 combined compounds, Amoxicillin/Clavulanate and Piperacillin/Tazobactam, are not displayed correctly: for the combination of Amoxi/Clav, only Amoxicillin is shown, whereas for Pip/Tazo only Tazo is shown.

**Comment by fxstr** [comment]
![image](https://cloud.githubusercontent.com/assets/1211144/7681760/0c37f8bc-fd73-11e4-8d62-08535862ff76.png)
I wrongfully took the first substance's name, not the antibiotic's.

**Comment by alpascal** [comment]
Your screenshot looks good! Could this be uploaded to infect.in (as I'm always a bit embarrassed to present infect to my colleagues with these obvious errors...)?

**Comment by fxstr** [comment]
@eventEmitter Could you release?

**Comment by alpascal** [comment]
You guys are the best :-)

**Comment by eventEmitter** [comment]
released. you may have to force reload.
