### ISSUE TITLE
Add diagnosis to filter

### ISSUE THREAD

**Issue by fxstr** [joinbox/infect#31]

**Comment by fxstr** [comment]
![image](https://cloud.githubusercontent.com/assets/1211144/9958351/2c2fac54-5e09-11e5-88b9-bb7536c764b8.png)

**Comment by fxstr** [comment]
Done. @alpascal Please test intensely and add some more diagnosis :fuelpump:

**Comment by alpascal** [comment]
Just had a quick peek at it, and it looks really good so far, so good job!!!

Will add more data, and test extensively as soon as I'm in London and settled in! I'm still determined to create the short introductory video for INFECT before the anresis.ch steering committee meeting and use it there as well!

**Comment by alpascal** [comment]
So far this seems to work perfectly, so this issue is closed for now :-)

**Comment by fxstr** [comment]
:checkered_flag:
